- Using numpy and creating arrays

In [4]:
import numpy as np

In [5]:
mylist = [1,2,3,4,5]

In [6]:
array1=np.array(mylist)

In [7]:
array1

array([1, 2, 3, 4, 5])

In [8]:
array1.shape

(5,)

using .shape instead of .shape() since shape is an attribute

In [9]:
array1.size

5

same for .size

- Creating a 2D array

In [10]:
mylist2 = [[1,2,3,4], [5,6,7,8], [9,10,11,12]] #nested list

In [11]:
array2 = np.array(mylist2)

In [12]:
array2

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [13]:
array2.ndim #dimension

2

In [14]:
array2.shape

(3, 4)

In [15]:
array2.size

12

- Creating arrays using arange

In [16]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [17]:
#creating a 1d array with 10 elements using arrange

In [18]:
#format (start, stop, increment)

In [19]:
np.zeros(5) #crreating a 1d array with every element 0 and float type

array([0., 0., 0., 0., 0.])

In [20]:
np.zeros(shape=(4,5))#creating a 2d 4x5 zero array

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [21]:
np.ones(3) #1d arrey with each element 1 and float type

array([1., 1., 1.])

In [22]:
#identity square array with diagonal elements 1
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

- Creating arrays using linspace

In [23]:
np.linspace(0,5,10) #creates a 10 element 1D array between 0 and 5 and each element is equally spaced

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

- Creation of arrays using random

In [24]:
np.random.rand(5) #creates a 1d array with 5 random values between 0 and 1

array([0.05197962, 0.28744463, 0.67395784, 0.95670092, 0.84783144])

In [25]:
np.random.randint(low = 1, high = 10, size = (3,4)) #creates a 2d array with random integer values between 1 and 10 of 3x4

array([[2, 6, 9, 8],
       [9, 8, 6, 2],
       [1, 8, 4, 2]])

In [26]:
np.random.randint(1,10, size = (3,4))

array([[3, 2, 5, 3],
       [6, 9, 9, 5],
       [2, 2, 6, 1]])

In [27]:
#the above two are same

In [28]:
np.random.randn(3,4) #creates a 2d array with random values under standard normal distribution

array([[ 0.55076772,  0.22855557, -0.81081212, -0.64576086],
       [ 0.45514867,  0.07558435,  0.06428916,  0.21033535],
       [ 0.54062868,  1.06313971, -0.99183868,  0.31291495]])

In [29]:
#reshaping array from 1D to 2D, where number of elements can't change

array3 = np.arange(0,15)

In [30]:
array3

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [31]:
array3.reshape(3,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [32]:
array3

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [33]:
#it just displays a 2d array and doesn't actually change it

In [34]:
array3.reshape(5,3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [35]:
array4 = array3.reshape(3,5)

In [36]:
array4

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [37]:
array4.mean()

7.0

In [38]:
np.mean(array4)

7.0

In [39]:
#the above two are the methods of finding mean of al elements in an array

In [40]:
#reshaping and then finding mean row wise
array5 = np.random.rand(8)

In [41]:
np.mean(array5.reshape(2,4), axis = 0) #row wise mean

array([0.51635672, 0.5288305 , 0.22771067, 0.44660423])

In [42]:
#reshaping and then finding mean column wise

In [44]:
np.mean(array5.reshape(2,4), axis = 1) #column wise

array([0.23739553, 0.62235554])

- in row wise and column wise mean, no. of output in row wise = no. of columns and no. of output in column wise = no. of rows

In [49]:
np.sum(array5.reshape(2,4), axis = 0) #sum row wise

array([1.03271345, 1.05766101, 0.45542135, 0.89320846])

In [51]:
np.sum(array5.reshape(2,4), axis = 1) #sum column wise

array([0.94958211, 2.48942216])

In [52]:
np.std(array5) #gives standard deviation

0.24986481868092839

In [53]:
#if we specify axis, we can find standard deviation row wise and column wise

- Indexing and slicing

In [55]:
array1 = np.arange(1,16)

In [56]:
array1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [57]:
array1[4]

5

In [58]:
array1[2:]

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [64]:
array1[0:6] #displaying the first 5 elements

array([1, 2, 3, 4, 5, 6])

In [65]:
array1[::2] #displaying every 2nd element

array([ 1,  3,  5,  7,  9, 11, 13, 15])

- Indexing and slicing in 2D array

In [66]:
twod_array1 = ([[5,10,15,20],[6,12,18,24], [7,14,21,28]])

In [70]:
twod_array = np.array(twod_array1)

In [71]:
#displaying first two rows
twod_array1[0:2]

[[5, 10, 15, 20], [6, 12, 18, 24]]

In [74]:
twod_array[0:2,1:3] #row 1,2 and column 2,3

array([[10, 15],
       [12, 18]])

In [75]:
twod_array[1:,1:]

array([[12, 18, 24],
       [14, 21, 28]])

In [76]:
#for just priting columns
twod_array[:,0]

array([5, 6, 7])

In [77]:
#conditional slicing

In [78]:
array2 = np.arange(0,5)

In [79]:
array2[array2<4]

array([0, 1, 2, 3])

- Joining two arrays

In [84]:
array_to_join = np.array([[5,10,15,20],[6,12,18,24], [7,14,21,28]])

In [86]:
np.concatenate((twod_array,array_to_join), axis = 1) #joining at the column

array([[ 5, 10, 15, 20,  5, 10, 15, 20],
       [ 6, 12, 18, 24,  6, 12, 18, 24],
       [ 7, 14, 21, 28,  7, 14, 21, 28]])

In [87]:
np.concatenate((twod_array,array_to_join), axis = 0) #joining at the row

array([[ 5, 10, 15, 20],
       [ 6, 12, 18, 24],
       [ 7, 14, 21, 28],
       [ 5, 10, 15, 20],
       [ 6, 12, 18, 24],
       [ 7, 14, 21, 28]])